// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
  apiSidebar: [
    'api/index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        "api/getting-started/authentication",
        "api/getting-started/first-api"
      ]
    },
    "api/drivers",
    "api/jobs",
    "api/routes",
    "api/scenarios",
    "api/statistics",
    "api/live",
    "api/skills",
    "api/simulation",
    "api/events",
    "api/slots",
    "api/notifications",
    "api/socials",
    "api/sessions"
  ],

  gateway: [
    'gateway/index',
    'gateway/connection',
    'gateway/protocol',
    {
      type: 'category',
      label: 'Events',
      items: [
        "gateway/events/index",
        "gateway/events/authentication",
        "gateway/events/auth-acknowledgement",
        "gateway/events/player-data",
        "gateway/events/player-online",
        "gateway/events/player-offline",
        "gateway/events/new-event"
      ]
    }
  ],

  webhooks: [
    'webhooks/index'
  ],
  
  discord: [
    'discord/index',
    'discord/rich-presence'
  ],
  
  typedefs: [
    'typedefs/index',
    'typedefs/vtc-object',
    'typedefs/job-object',
    'typedefs/route-object',
    'typedefs/scenario-object',
    'typedefs/driver',
    'typedefs/player-online',
    'typedefs/player-offline',
    'typedefs/ferry',
    'typedefs/fine',
    'typedefs/refuel-paid',
    'typedefs/train',
    'typedefs/job-started',
    'typedefs/job-cancelled',
    'typedefs/collision',
    // 'typedefs/repair',
    'typedefs/skills-object',
    'typedefs/simulation-object',
    'typedefs/milestone-object',
    'typedefs/simulation-job-object',
    'typedefs/simulation-finance-object',
    'typedefs/events-object',
    'typedefs/slots-object',
    'typedefs/notification-object',
    'typedefs/activity-object',
    'typedefs/session-object',
  ]
};

export default sidebars;
